version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: sport_data_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: strava_poc
    ports:
      - "5432:5432"
    # CRUCIAL : Active la réplication logique pour Debezium
    command: postgres -c wal_level=logical
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
    ports:
      - "19092:19092"
      - "9644:9644"

  debezium:
    image: quay.io/debezium/connect:latest
    container_name: debezium
    ports:
      - "8083:8083"
    environment:
      - BOOTSTRAP_SERVERS=redpanda:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    depends_on:
      - postgres
      - redpanda